//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuckyBallsData.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISqlService")]
    public interface ISqlService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetLotteryData", ReplyAction="http://tempuri.org/ISqlService/GetLotteryDataResponse")]
        string GetLotteryData(int issue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetAllLotteries", ReplyAction="http://tempuri.org/ISqlService/GetAllLotteriesResponse")]
        string GetAllLotteries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetLotteryCount", ReplyAction="http://tempuri.org/ISqlService/GetLotteryCountResponse")]
        int GetLotteryCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetLotteriesByIndex", ReplyAction="http://tempuri.org/ISqlService/GetLotteriesByIndexResponse")]
        string GetLotteriesByIndex(int index_from, int index_to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetLotteriesByIssue", ReplyAction="http://tempuri.org/ISqlService/GetLotteriesByIssueResponse")]
        string GetLotteriesByIssue(int issue_from, int issue_to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetDataVersion", ReplyAction="http://tempuri.org/ISqlService/GetDataVersionResponse")]
        string GetDataVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetAttributesTemplate", ReplyAction="http://tempuri.org/ISqlService/GetAttributesTemplateResponse")]
        string GetAttributesTemplate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetLatestAttributes", ReplyAction="http://tempuri.org/ISqlService/GetLatestAttributesResponse")]
        string GetLatestAttributes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetLatestReleaseInfo", ReplyAction="http://tempuri.org/ISqlService/GetLatestReleaseInfoResponse")]
        string GetLatestReleaseInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetMatrixTableItem", ReplyAction="http://tempuri.org/ISqlService/GetMatrixTableItemResponse")]
        string GetMatrixTableItem(int candidateCount, int selectCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetVersion", ReplyAction="http://tempuri.org/ISqlService/GetVersionResponse")]
        void GetVersion(ref int version, ref long revisions, ref int latestIssue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/RegisterUserChannel", ReplyAction="http://tempuri.org/ISqlService/RegisterUserChannelResponse")]
        void RegisterUserChannel(string userId, string channelUri, string platform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetUserChannels", ReplyAction="http://tempuri.org/ISqlService/GetUserChannelsResponse")]
        string[] GetUserChannels(string platform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/RememberUserLastLoginDate", ReplyAction="http://tempuri.org/ISqlService/RememberUserLastLoginDateResponse")]
        void RememberUserLastLoginDate(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetLatestSoftwareVersion", ReplyAction="http://tempuri.org/ISqlService/GetLatestSoftwareVersionResponse")]
        void GetLatestSoftwareVersion(ref int version, ref bool schemaChanged);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/GetReleaseNotes", ReplyAction="http://tempuri.org/ISqlService/GetReleaseNotesResponse")]
        string GetReleaseNotes(int fromVersion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISqlServiceChannel : LuckyBallsData.ServiceReference1.ISqlService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SqlServiceClient : System.ServiceModel.ClientBase<LuckyBallsData.ServiceReference1.ISqlService>, LuckyBallsData.ServiceReference1.ISqlService {
        
        public SqlServiceClient() {
        }
        
        public SqlServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SqlServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SqlServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SqlServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLotteryData(int issue) {
            return base.Channel.GetLotteryData(issue);
        }
        
        public string GetAllLotteries() {
            return base.Channel.GetAllLotteries();
        }
        
        public int GetLotteryCount() {
            return base.Channel.GetLotteryCount();
        }
        
        public string GetLotteriesByIndex(int index_from, int index_to) {
            return base.Channel.GetLotteriesByIndex(index_from, index_to);
        }
        
        public string GetLotteriesByIssue(int issue_from, int issue_to) {
            return base.Channel.GetLotteriesByIssue(issue_from, issue_to);
        }
        
        public string GetDataVersion() {
            return base.Channel.GetDataVersion();
        }
        
        public string GetAttributesTemplate() {
            return base.Channel.GetAttributesTemplate();
        }
        
        public string GetLatestAttributes() {
            return base.Channel.GetLatestAttributes();
        }
        
        public string GetLatestReleaseInfo() {
            return base.Channel.GetLatestReleaseInfo();
        }
        
        public string GetMatrixTableItem(int candidateCount, int selectCount) {
            return base.Channel.GetMatrixTableItem(candidateCount, selectCount);
        }
        
        public void GetVersion(ref int version, ref long revisions, ref int latestIssue) {
            base.Channel.GetVersion(ref version, ref revisions, ref latestIssue);
        }
        
        public void RegisterUserChannel(string userId, string channelUri, string platform) {
            base.Channel.RegisterUserChannel(userId, channelUri, platform);
        }
        
        public string[] GetUserChannels(string platform) {
            return base.Channel.GetUserChannels(platform);
        }
        
        public void RememberUserLastLoginDate(string userId) {
            base.Channel.RememberUserLastLoginDate(userId);
        }
        
        public void GetLatestSoftwareVersion(ref int version, ref bool schemaChanged) {
            base.Channel.GetLatestSoftwareVersion(ref version, ref schemaChanged);
        }
        
        public string GetReleaseNotes(int fromVersion) {
            return base.Channel.GetReleaseNotes(fromVersion);
        }
    }
}
