//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuckyBallsData.DBManageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBManageServiceReference.IDBManagement")]
    public interface IDBManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBManagement/PushNotification", ReplyAction="http://tempuri.org/IDBManagement/PushNotificationResponse")]
        void PushNotification(int platform, string message, string devices);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBManagementChannel : LuckyBallsData.DBManageServiceReference.IDBManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBManagementClient : System.ServiceModel.ClientBase<LuckyBallsData.DBManageServiceReference.IDBManagement>, LuckyBallsData.DBManageServiceReference.IDBManagement {
        
        public DBManagementClient() {
        }
        
        public DBManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PushNotification(int platform, string message, string devices) {
            base.Channel.PushNotification(platform, message, devices);
        }
    }
}
