//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSQLService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBHistoryEntity : DbContext
    {
        public DBHistoryEntity()
            : base("name=DBHistoryEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attribute> Attributes { get; set; }
        public DbSet<Basic> Basics { get; set; }
        public DbSet<Detail> Details { get; set; }
        public DbSet<Omission> Omissions { get; set; }
    }
}
