//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSQLService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int Issue { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Prize1Bonus { get; set; }
        public decimal Prize2Bonus { get; set; }
        public int Prize1Count { get; set; }
        public int Prize2Count { get; set; }
        public int Prize3Count { get; set; }
        public int Prize4Count { get; set; }
        public int Prize5Count { get; set; }
        public int Prize6Count { get; set; }
        public int BetAmount { get; set; }
        public int PoolAmount { get; set; }
        public string More { get; set; }
    }
}
