//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSQLService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extend
    {
        public int Issue { get; set; }
        public int Sum { get; set; }
        public int Omission { get; set; }
        public int ContinuousNumCount { get; set; }
        public int EvenNumCount { get; set; }
        public int SmallNumCount { get; set; }
        public int PrimeNumCount { get; set; }
        public int RepeatNumCount { get; set; }
        public string RedNumHitStatus { get; set; }
        public string RedNumOmissionStatus { get; set; }
        public string BlueNumHitStatus { get; set; }
        public string BlueNumOmissionStatus { get; set; }
    }
}
