//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSQLService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LottoBasic
    {
        public int Issue { get; set; }
        public int Red1 { get; set; }
        public int Red2 { get; set; }
        public int Red3 { get; set; }
        public int Red4 { get; set; }
        public int Red5 { get; set; }
        public int Red6 { get; set; }
        public int Blue { get; set; }
        public System.DateTime Date { get; set; }
    }
}
