//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSQLService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Omission
    {
        public int Issue { get; set; }
        public int Red_01_Hit { get; set; }
        public int Red_02_Hit { get; set; }
        public int Red_03_Hit { get; set; }
        public int Red_04_Hit { get; set; }
        public int Red_05_Hit { get; set; }
        public int Red_06_Hit { get; set; }
        public int Red_07_Hit { get; set; }
        public int Red_08_Hit { get; set; }
        public int Red_09_Hit { get; set; }
        public int Red_10_Hit { get; set; }
        public int Red_11_Hit { get; set; }
        public int Red_12_Hit { get; set; }
        public int Red_13_Hit { get; set; }
        public int Red_14_Hit { get; set; }
        public int Red_15_Hit { get; set; }
        public int Red_16_Hit { get; set; }
        public int Red_17_Hit { get; set; }
        public int Red_18_Hit { get; set; }
        public int Red_19_Hit { get; set; }
        public int Red_20_Hit { get; set; }
        public int Red_21_Hit { get; set; }
        public int Red_22_Hit { get; set; }
        public int Red_23_Hit { get; set; }
        public int Red_24_Hit { get; set; }
        public int Red_25_Hit { get; set; }
        public int Red_26_Hit { get; set; }
        public int Red_27_Hit { get; set; }
        public int Red_28_Hit { get; set; }
        public int Red_29_Hit { get; set; }
        public int Red_30_Hit { get; set; }
        public int Red_31_Hit { get; set; }
        public int Red_32_Hit { get; set; }
        public int Red_33_Hit { get; set; }
        public int Red_01_Omission { get; set; }
        public int Red_02_Omission { get; set; }
        public int Red_03_Omission { get; set; }
        public int Red_04_Omission { get; set; }
        public int Red_05_Omission { get; set; }
        public int Red_06_Omission { get; set; }
        public int Red_07_Omission { get; set; }
        public int Red_08_Omission { get; set; }
        public int Red_09_Omission { get; set; }
        public int Red_10_Omission { get; set; }
        public int Red_11_Omission { get; set; }
        public int Red_12_Omission { get; set; }
        public int Red_13_Omission { get; set; }
        public int Red_14_Omission { get; set; }
        public int Red_15_Omission { get; set; }
        public int Red_16_Omission { get; set; }
        public int Red_17_Omission { get; set; }
        public int Red_18_Omission { get; set; }
        public int Red_19_Omission { get; set; }
        public int Red_20_Omission { get; set; }
        public int Red_21_Omission { get; set; }
        public int Red_22_Omission { get; set; }
        public int Red_23_Omission { get; set; }
        public int Red_24_Omission { get; set; }
        public int Red_25_Omission { get; set; }
        public int Red_26_Omission { get; set; }
        public int Red_27_Omission { get; set; }
        public int Red_28_Omission { get; set; }
        public int Red_29_Omission { get; set; }
        public int Red_30_Omission { get; set; }
        public int Red_31_Omission { get; set; }
        public int Red_32_Omission { get; set; }
        public int Red_33_Omission { get; set; }
        public int Red_01_Temperature { get; set; }
        public int Red_02_Temperature { get; set; }
        public int Red_03_Temperature { get; set; }
        public int Red_04_Temperature { get; set; }
        public int Red_05_Temperature { get; set; }
        public int Red_06_Temperature { get; set; }
        public int Red_07_Temperature { get; set; }
        public int Red_08_Temperature { get; set; }
        public int Red_09_Temperature { get; set; }
        public int Red_10_Temperature { get; set; }
        public int Red_11_Temperature { get; set; }
        public int Red_12_Temperature { get; set; }
        public int Red_13_Temperature { get; set; }
        public int Red_14_Temperature { get; set; }
        public int Red_15_Temperature { get; set; }
        public int Red_16_Temperature { get; set; }
        public int Red_17_Temperature { get; set; }
        public int Red_18_Temperature { get; set; }
        public int Red_19_Temperature { get; set; }
        public int Red_20_Temperature { get; set; }
        public int Red_21_Temperature { get; set; }
        public int Red_22_Temperature { get; set; }
        public int Red_23_Temperature { get; set; }
        public int Red_24_Temperature { get; set; }
        public int Red_25_Temperature { get; set; }
        public int Red_26_Temperature { get; set; }
        public int Red_27_Temperature { get; set; }
        public int Red_28_Temperature { get; set; }
        public int Red_29_Temperature { get; set; }
        public int Red_30_Temperature { get; set; }
        public int Red_31_Temperature { get; set; }
        public int Red_32_Temperature { get; set; }
        public int Red_33_Temperature { get; set; }
        public int Blue_01_Hit { get; set; }
        public int Blue_02_Hit { get; set; }
        public int Blue_03_Hit { get; set; }
        public int Blue_04_Hit { get; set; }
        public int Blue_05_Hit { get; set; }
        public int Blue_06_Hit { get; set; }
        public int Blue_07_Hit { get; set; }
        public int Blue_08_Hit { get; set; }
        public int Blue_09_Hit { get; set; }
        public int Blue_10_Hit { get; set; }
        public int Blue_11_Hit { get; set; }
        public int Blue_12_Hit { get; set; }
        public int Blue_13_Hit { get; set; }
        public int Blue_14_Hit { get; set; }
        public int Blue_15_Hit { get; set; }
        public int Blue_16_Hit { get; set; }
        public int Blue_01_Omission { get; set; }
        public int Blue_02_Omission { get; set; }
        public int Blue_03_Omission { get; set; }
        public int Blue_04_Omission { get; set; }
        public int Blue_05_Omission { get; set; }
        public int Blue_06_Omission { get; set; }
        public int Blue_07_Omission { get; set; }
        public int Blue_08_Omission { get; set; }
        public int Blue_09_Omission { get; set; }
        public int Blue_10_Omission { get; set; }
        public int Blue_11_Omission { get; set; }
        public int Blue_12_Omission { get; set; }
        public int Blue_13_Omission { get; set; }
        public int Blue_14_Omission { get; set; }
        public int Blue_15_Omission { get; set; }
        public int Blue_16_Omission { get; set; }
        public int Blue_01_Temperature { get; set; }
        public int Blue_02_Temperature { get; set; }
        public int Blue_03_Temperature { get; set; }
        public int Blue_04_Temperature { get; set; }
        public int Blue_05_Temperature { get; set; }
        public int Blue_06_Temperature { get; set; }
        public int Blue_07_Temperature { get; set; }
        public int Blue_08_Temperature { get; set; }
        public int Blue_09_Temperature { get; set; }
        public int Blue_10_Temperature { get; set; }
        public int Blue_11_Temperature { get; set; }
        public int Blue_12_Temperature { get; set; }
        public int Blue_13_Temperature { get; set; }
        public int Blue_14_Temperature { get; set; }
        public int Blue_15_Temperature { get; set; }
        public int Blue_16_Temperature { get; set; }
    }
}
