//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSQLService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedObmission
    {
        public int Issue { get; set; }
        public Nullable<long> RowInx { get; set; }
        public Nullable<long> C01 { get; set; }
        public Nullable<long> C02 { get; set; }
        public Nullable<long> C03 { get; set; }
        public Nullable<long> C04 { get; set; }
        public Nullable<long> C05 { get; set; }
        public Nullable<long> C06 { get; set; }
        public Nullable<long> C07 { get; set; }
        public Nullable<long> C08 { get; set; }
        public Nullable<long> C09 { get; set; }
        public Nullable<long> C10 { get; set; }
        public Nullable<long> C11 { get; set; }
        public Nullable<long> C12 { get; set; }
        public Nullable<long> C13 { get; set; }
        public Nullable<long> C14 { get; set; }
        public Nullable<long> C15 { get; set; }
        public Nullable<long> C16 { get; set; }
        public Nullable<long> C17 { get; set; }
        public Nullable<long> C18 { get; set; }
        public Nullable<long> C19 { get; set; }
        public Nullable<long> C20 { get; set; }
        public Nullable<long> C21 { get; set; }
        public Nullable<long> C22 { get; set; }
        public Nullable<long> C23 { get; set; }
        public Nullable<long> C24 { get; set; }
        public Nullable<long> C25 { get; set; }
        public Nullable<long> C26 { get; set; }
        public Nullable<long> C27 { get; set; }
        public Nullable<long> C28 { get; set; }
        public Nullable<long> C29 { get; set; }
        public Nullable<long> C30 { get; set; }
        public Nullable<long> C31 { get; set; }
        public Nullable<long> C32 { get; set; }
        public Nullable<long> C33 { get; set; }
    }
}
